"""
This program was developed as part of the Master's project research.

Description
-----------
The initial atomic velocity components are generated from the Maxwell-Boltzmann distribution
using pseudo-random numbers generated by a Linear Congruential Generator (LCG) and the
Box-Muller transform.

Linear Congruential Generator -> Box-Muller -> Maxwell-Boltzmann distribution.

Input
-----
 - Molecular structure file XYZ.

Output
------
 - New XYZ file with the initial atomic velocity components.

Usage
-----
    python initial_velocities.py --file <input_file>.xyz

    python initial_velocities.py --file <input_file>.xyz --temperature 350 

    python initial_velocities.py --file <input_file>.xyz --temperature 420 --output <output>.xyz

References
----------
    Leach, A. R. Molecular Modelling: Principles and Applications.
    Prentice Hall, 2nd ed., 2001.
 
    Box, G. E. P.; Muller, M. E. A Note on the Generation of Random
    Normal Deviates. The Annals of Mathematical Statistics, v. 29,
    n. 2, p. 610-611, 1958.

"""
import sys
from pathlib import Path
import re

# Command-line arguments.
import argparse
import textwrap
from functools import partial

# Constants
import constants

# Numpy
import numpy as np

#
# About program
# 
NAME = "initial_velocities"
VERSION = "0.0.1"
AUTHOR = "Rogério Ribeiro Macêdo"
GITHUB = "https://github.com/rogerioribeiromacedo"
LINKEDIN = "https://linkedin.com/in/rogerioribeiromacedo"
DESCRIPTION = """The objective of this program is to generate the initial atomic velocities from
the Maxwell-Boltzmann distribution using pseudo-random numbers generated by a Lineaar Congruential 
Generator (LCG) and the Box-Muller transform. The program reads an XYZ file containing the 
atomic positions and generates a new XYZ file with the initial atomic velocity components.
"""
USAGE="""python initial_velocities.py --file <input_file>.xyz

python initial_velocities.py --file <input_file>.xyz --temperature <value>

python initial_velocities.py --file <input_file>.xyz --temperature <value> --output <output>.xyz

python initial_velocities.py --about
"""

class Atom:
    def __init__(self,
                 symbol: str,
                 mass: float,
                 pos_x: float,
                 pos_y: float,
                 pos_z: float) -> None:
        """
        Represents a single atom with position and velocity.

        Parameters
        ----------
        symbol : str
            Atomic symbol (e.g. 'C', 'H', 'O').
        mass : float
            Atomic mass in atomic mass units (amu).
        pos_x : float
            Position in x-direction in Angstroms.
        pos_y : float
            Position in y-direction in Angstroms.
        pos_z : float
            Position in z-direction in Angstroms.
        """
        self.symbol = symbol
        self.mass   = mass
        self.pos_x  = pos_x
        self.pos_y  = pos_y
        self.pos_z  = pos_z

        # Velocities are set later by the MB generator
        self.vel_x: float = 0.0
        self.vel_y: float = 0.0
        self.vel_z: float = 0.0

    def set_velocities(self, vx: float, vy: float, vz: float) -> None:
        """
        Set the three velocity components at once.

        Parameters
        ----------
        vx : float
            Velocity in x-direction.
        vy : float
            Velocity in y-direction.
        vz : float
            Velocity in z-direction.
        """
        self.vel_x = vx
        self.vel_y = vy
        self.vel_z = vz

    def __repr__(self) -> str:
        return (
            f"Atom({self.symbol}, m={self.mass:.4f}, "
            f"pos=({self.pos_x:.4f}, {self.pos_y:.4f}, {self.pos_z:.4f}), "
            f"vel=({self.vel_x:.4f}, {self.vel_y:.4f}, {self.vel_z:.4f}))")

class LinearCongruentialGenerator:    
    def __init__(self,
                 seed: int = 123456,
                 a: int = 1664525,
                 c: int = 1013904223,
                 m: int = 2**32) -> None:
        """
        Linear Congruential Generator (LCG) for pseudo-random number generation.

        The recurrence relation is: x_(n+1) = (a * x_n + c) mod m

        Parameters
        ----------
        seed : int, optional
            Initial state of the generator. Default: 123456.
        a : int, optional
            Multiplier. Default: 1664525 (Numerical Recipes).
        c : int, optional
            Increment. Default: 1013904223 (Numerical Recipes).
        m : int, optional
            Modulus. Default: 2**32.
        """
        self.state = seed
        self.a = a
        self.c = c
        self.m = m

    def random_int(self) -> int:
        """
        Generate the next pseudo-random integer in the sequence.

        Returns
        -------
        int
            Pseudo-random integer in the range [0, m).
        """
        self.state = (self.a * self.state + self.c) % self.m
        return self.state
    
    def random_norm(self) -> float:
        """
        Generate the next pseudo-random number normalized to [0, 1).

        Returns
        -------
        float
            Pseudo-random float in the range [0, 1).
        """
        return self.random_int() / self.m

def show_about() -> None:
    """
    Display information about the program.
   
    Returns
    -------
    None

    """
    print("=" * 75)
    print(f"{NAME}  (v{VERSION})")
    print("=" * 75)

    print(f"Author   : {AUTHOR}")
    print(f"GitHub   : {GITHUB}")
    print(f"LinkedIn : {LINKEDIN}")

    print("\nDescription")
    print("-" * 75)
    print(textwrap.fill(DESCRIPTION, width=75))

    print("\nUsage")
    print("-" * 75)
    print(textwrap.dedent(USAGE))

    print("=" * 75)

def print_header() -> None:
    """
    Print the header of the program.

    Returns
    -------
    None

    """
    header = textwrap.dedent(
        '''
        | ---------------------------------------------------------------------------------------
        |
        | Initial velocities generator program
        |
        | ---------------------------------------------------------------------------------------
        | Computes the initial atomic velocity components from the Maxwell-Boltzmann distribution
        | ---------------------------------------------------------------------------------------
        '''
    )
    print(header)

def positive_temperature(value: str) -> float:
    """
    Guarantee that temperature is a real number strictly positive.

    Parameters
    ----------
    value: str
        Temperature informed.

    Returns
    -------
    float
        Temperature in Kelvin

    """
    try:
        t = float(value)
    except ValueError:
        raise argparse.ArgumentTypeError(
            f"'{value}' is not a valid number for temperature."
        )
    if t <= 0.0:
        raise argparse.ArgumentTypeError(
            f"Temperature must be strictly positive. Received: {value} K"
        )
    
    return t

def valid_file(value: str, expected_ext: list[str]) -> Path:
    """
    Validate the existence and extension of an input file.

    Parameters
    ----------
    value : str
        Path to the file provided by the user.
    expected_ext : list[str]
        Expected file extensions (e.g., ['.pdb', '.xyz', ...])

    Returns
    -------
    Path
        A Path object pointing to the file.

    """
    path = Path(value)

    # File or path not found
    if not path.exists():
        raise argparse.ArgumentTypeError(
            f"File or path not found: {str(path)}"
        )

    # Is file
    if not path.is_file():
        raise argparse.ArgumentTypeError(
            f"Not a file: {str(path)}"
        )
    
    # Suffix
    if path.suffix not in expected_ext:
        raise argparse.ArgumentTypeError(
            f"Expected a file with one of the following extensions: '{expected_ext}' file, got '{path.suffix}'"
        )
    
    return path

def valid_output(value: str, expected_ext: list[str]) -> Path:
    """
    Validate the existence of the directory.

    Parameters
    ----------
    value: str
        Path to the output file provided by the user.
    expected_ext : list[str]
        Expected file extensions (e.g., ['.pdb', '.xyz', ...])
        
    Returns
    -------
    Path
        A Path object pointing to the output file.    

    """
    path = Path(value)

    # Directory not found
    if not path.parent.exists():
        print(f"Error: directory not found: {str(path.parent)}")
        sys.exit(1)

    # Suffix
    if path.suffix not in expected_ext:
        raise argparse.ArgumentTypeError(
            f"Expected a file with one of the following extensions: '{expected_ext}' file, got '{path.suffix}'"
        )

    return path

def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.

    Returns
    -------
    argparse.Namespace
        Parsed commnad-line arguments

    """
    parser = argparse.ArgumentParser(
        prog="initial_velocities",
        description="Generate initial atomic velocities from the Maxwell-Boltzmann distribution"
    )
    #
    # Optional arguments
    #
    optional = parser.add_argument_group(
        title="Optional",
        description="Optional arguments."
    )
    optional.add_argument(
        "-T", "--temperature",
        metavar="TEMP",
        type=positive_temperature,
        default=298.15,
        help="Temperature in Kelvin for the MB distribution. (default: 298.15 K)"
    )
    optional.add_argument(
        "-o", "--output",
        type=partial(valid_output, expected_ext=[".xyz"]),
        help="Output file name for the .xyz file with initial velocities.."
    )
    optional.add_argument(
        "-a", "--about",
        action="store_true",
        help="Show information about the program."
    )

    #
    # Required arguments
    #
    required = parser.add_argument_group(
        title="Required",
        description="Required arguments"
    )
    required.add_argument(
        "--file",
        required=True,
        metavar="FILE",
        type=partial(valid_file, expected_ext=[".xyz"]),
        help="Path to the input molecular structure file (XYZ)."
    )
    parsed = parser.parse_args()

    return parsed

def adjust_velocities(atoms: list[Atom]) -> list[Atom]:
    """
    Remove the center-of-mass velocity to ensure zero total linear momentum.

    Parameters
    ----------
    atoms : list[Atom]
        List of atoms with velocities set.

    Returns
    -------
    list[Atom]
        The same list with corrected velocities.
    """
    # Total mass
    total_mass = sum(atom.mass for atom in atoms)
    
    # New velocities
    vcm_x = sum(atom.mass * atom.vel_x for atom in atoms) / total_mass
    vcm_y = sum(atom.mass * atom.vel_y for atom in atoms) / total_mass
    vcm_z = sum(atom.mass * atom.vel_z for atom in atoms) / total_mass

    for atom in atoms:
        atom.vel_x -= vcm_x
        atom.vel_y -= vcm_y
        atom.vel_z -= vcm_z

    return atoms

def valid_momentum(atoms: list[Atom]) -> bool:
    """
    Verify if the total linear momentum of the system is zero.

    Parameters
    ----------
    atoms : list[Atom]
        List of atoms with velocities already set.
    
    Returns
    -------
    bool
        True if total momentum is zero within tolerance.
    """
    momentum_zero = False
    px = sum(atom.mass * atom.vel_x for atom in atoms)
    py = sum(atom.mass * atom.vel_y for atom in atoms)
    pz = sum(atom.mass * atom.vel_z for atom in atoms)
        
    if (np.round(px) == 0.0) and (np.round(py) == 0.0) and (np.round(pz) == 0.0):
        momentum_zero = True
    
    return momentum_zero

def read_file_xyz(file_xyz: Path, temp: float) -> list[Atom]:
    """
    Read an XYZ file and return a list of Atom objects.

    Parameters
    ----------
    file_xyz: Path
        Path to the XYZ file containing atomic positions.

    Returns
    -------
    list[Structure]
        List of Atom objects.

    """
    # All atoms in XYZ file
    atoms = []

    # Counting atoms in file
    num_atoms = 0

    # Pseudo-number generator
    num_pseudo_aleat = LinearCongruentialGenerator()

    with open(file_xyz, "r") as f_xyz:
        # Reading the two first lines
        try:
            v = f_xyz.readline()
            file_xyz_number_atoms = int(v)
        except ValueError:
            print(f"The first line of the XYZ file must be the number of atoms in the structure.")
            sys.exit(0)
        file_xyz_comments = f_xyz.readline()

        print(f"  - Reading lines...")
        for line in f_xyz:
            # Reading and spliting line
            values = re.split(r"\s{1,}", line.strip())
            num_atoms += 1
            
            # Get and validate symbol
            v_symbol = values[0]
            if not v_symbol in constants.ATOMIC_MASSES:
                raise Exception(
                    f"{v_symbol} is not a valid atomic symbol."
                )
            v_mass = constants.ATOMIC_MASSES[v_symbol]

            # Initializing position variables
            v_pos_x = 0.0
            v_pos_y = 0.0
            v_pos_z = 0.0
            
            # Get positions
            try:
                v_pos_x = float(values[1])
                v_pos_y = float(values[2])
                v_pos_z = float(values[3])
            except ValueError:
                print("")
                print(f"Error: An invalid value for atomic positions was found: {v_symbol} {v_pos_x} {v_pos_y} {v_pos_z}")
                sys.exit(1)

            # 
            # Initial velocities
            #
            sigma = np.sqrt((constants.KB*temp) / v_mass)
            
            # x
            epsilon1 = num_pseudo_aleat.random_norm()
            epsilon2 = num_pseudo_aleat.random_norm()
            x1 = np.sqrt(-2.0 * np.log(epsilon1)) * np.cos(2.0 * np.pi * epsilon2)
            v_vel_x = sigma * x1

            # y
            x2 = np.sqrt(-2.0 * np.log(epsilon1)) * np.sin(2.0 * np.pi * epsilon2)
            v_vel_y = sigma * x2

            # z
            epsilon3 = num_pseudo_aleat.random_norm()
            epsilon4 = num_pseudo_aleat.random_norm()
            x3 = np.sqrt(-2.0 * np.log(epsilon3)) * np.cos(2.0 * np.pi * epsilon4)
            v_vel_z = sigma * x3

            #
            # Atom
            #
            atom = Atom(symbol=v_symbol,
                        mass=v_mass,
                        pos_x=v_pos_x,
                        pos_y=v_pos_y,
                        pos_z=v_pos_z)
            atom.vel_x = v_vel_x
            atom.vel_y = v_vel_y
            atom.vel_z = v_vel_z
            
            atoms.append(atom)

    # Validate the atom count against the value read from the header file.
    if len(atoms) != file_xyz_number_atoms:
        print(f"Error: expect {file_xyz_number_atoms} atoms, but read {len(atoms)}.")
        sys.exit(1)
    
    # The total momentum of the system is zero
    print(f"  - Adjust velocities.")
    atoms_new = adjust_velocities(atoms)    

    # Return
    return atoms_new

def saving_new_xyz_file(new_xyz_file: Path, atoms: list[Atom], ) -> None:
    """
    Saving new XYZ file with velocities.

    Returns
    -------
    None

    """
    with open(new_xyz_file, "w") as f_xyz:
        f_xyz.write(f"{len(atoms)}\n")
        f_xyz.write(f"{new_xyz_file.name}\n")
        for atom in atoms:
            line = f"{atom.symbol:<10} {atom.pos_x:> 2.5f} {atom.pos_y:> 2.5f} {atom.pos_z:> 2.5f} {atom.vel_x:> 2.5f} {atom.vel_y:> 2.5f} {atom.vel_z:> 2.5f}\n"
            f_xyz.write(line)

def main() -> None:
    """
    Main function to produce the initial atomic velocities from the Maxwell-Boltzmann distribution.

    Returns
    ------
    None

    """
    # Arguments
    if "--about" in sys.argv or "-a" in sys.argv:
        show_about()
        sys.exit(0)
    args = parse_args()

    # Print header
    print_header()

    # Reading XYZ
    print("")
    print(f"+ Reading XYZ file.")
    atoms = read_file_xyz(args.file,
                          args.temperature)
    
    # Momentum    
    if not valid_momentum(atoms):
        print("")
        print("+ Total momentum is not zero!")
    else:
        print("")
        print(f"+ The total momentum of the system is zero.")

    #
    # Saving new XYZ file
    #
    if args.output:
        output = args.output
    else:
        output = Path(str(args.file.parent) + "\\" + args.file.stem + f"_velocities_{args.temperature}.xyz")
    print("")
    print("+ Saving new file:")
    saving_new_xyz_file(output, atoms)
    print(f"  - Path........: {output.parent}")
    print(f"  - Output file.: {output.name}")

if __name__ == "__main__":
    main()
